[wrapper] colors !

diff --git a/bin/anananas b/bin/anananas
--- a/bin/anananas
+++ b/bin/anananas
@@ -1,3 +1,68 @@
-#!/bin/sh
 
-ant -logger org.apache.tools.ant.listener.AnsiColorLogger $@
+#!/bin/bash
+
+# ant -emacs  $@
+
+# Prettify ant output
+#
+# Author: Björn Husberg (bjorn@husberg.se)
+# https://github.com/bjornhusberg/colorant
+
+# Ansi colors
+RESET=$(echo -en "\033[0m")
+BOLD=$(echo -en "\033[1m")
+RED=$(echo -en "\033[1;31m")
+YELLOW=$(echo -en "\033[1;33m")
+PURPLE=$(echo -en "\033[1;35m")
+CYAN=$(echo -en "\033[1;36m")
+GREEN=$(echo -en "\033[1;32m")
+BLUE=$(echo -en "\033[1;34m")
+
+function addRegexp() {
+  if [ "$REGEXP" != "" ]; then
+    REGEXP="$REGEXP;"
+  fi
+  REGEXP="${REGEXP}s/$1/$2&$RESET/g"
+}
+
+# Bold target labels
+addRegexp "^[[[:alnum:]\-]*]*:" "$BOLD"
+
+# Bold task labels
+addRegexp "\[[[:alnum:]\-]*\]" "$CYAN"
+
+# Cyan info
+addRegexp "INFO" "$CYAN"
+
+# Red errors
+addRegexp "ERROR" "$RED"
+addRegexp "FATAL" "$RED"
+addRegexp "SEVERE" "$RED"
+
+# Yellow warnings
+addRegexp "WARNING" "$YELLOW"
+
+# Green build success
+addRegexp "BUILD SUCCESS\(FUL\)\{0,1\}" "$GREEN"
+
+# Bold paths
+addRegexp "\(\/[[:alnum:]._-]\{1,\}\)\{2,\}" "$BOLD"
+
+# Red exceptions
+addRegexp "\([[:lower:]][[:alnum:]]*\.\)*[[:alpha:]]*[[:alnum:]]*Exception" "$RED"
+
+# Red errors
+addRegexp "[Ee]rrors\{0,1\}" "$RED"
+
+# Red failed
+addRegexp "[Ff]ailed" "$RED"
+
+# Red fail, failure, failures
+addRegexp "[Ff]ail\(ures\{0,1\}\)\{0,1\}" "$RED"
+
+# Yellow warn, warning, warnings
+addRegexp "[Ww]arn\(ings\{0,1\}\)\{0,1\}" "$YELLOW"
+
+ant -logger org.apache.tools.ant.listener.SimpleBigProjectLogger "$@" | sed -e "$REGEXP"
+
+exit ${PIPESTATUS[0]}
